const intent = 'greetings';
const expressions = [
    'heeeello',
    'h3llo',
    'heyy',
    'heyo',
    'Boot Up',
    'Aloa',
    'Hola',
    'helo',
    'Coucou',
    'hiii',
    'Ciao',
    'Good Morning Théo',
    'Hey you',
    'helllloooo',
    'begin',
    '/start',
    'bonjour',
    'Howdie',
    'aloha',
    'Yop',
    'Hello Ava !',
    'Hey Francois',
    'Yoooo',
    'Hello Oliver',
    'good morning',
    'Morning !',
    'hey body',
    'hi bot',
    'Hi dude',
    'hey bot',
    'Hello my friend',
    'Welcome !',
    'Howdy',
    "mornin' mister",
    'Hello there !',
    'Well hello there',
    'Yo buddy',
    'Helloooooooo',
    'hey',
    'hello',
    'Hi there',
    'Hello',
    'Goodmorning!',
    'Welcome',
    'Hi',
    'Hello you!',
    'Yo',
    'Hello, good afternoon !',
    'good afternoon',
    'Good morning',
    'how are you today?'
];

module.exports = {
    expressions,
    intent
}